version: '3.8'

services:
  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    user: "1001:1001"
    command: ["run", "--config=/home/gitlab-runner/config.toml", "--working-directory=/home/gitlab-runner"]
    environment:
      - TZ=Europe/Istanbul
      - HOME=/home/gitlab-runner
    volumes:
      - ${PODMAN_SOCK_PATH}:/var/run/docker.sock
      - ./gitlabrunner/home:/home/gitlab-runner:Z
    networks:
      cloud_internal:
        aliases:
          - gitlab-runner
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

networks:
  cloud_internal:
    external: true
