version: '3.8'

services:
  pufferpanel:
    image: docker.io/pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    user: "0:0"
    # ports:
    #   - "5657:5657" # SFTP port for file transfer
    volumes:
      - pufferpanel_config:/etc/pufferpanel
      - pufferpanel_data:/var/lib/pufferpanel
      # This line is required for PufferPanel to be able to create isolated Docker containers internally:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      - PUFFER_PANEL_REVERSE_PROXY=true
    
    security_opt:
      - label=disable

    networks:
      cloud_internal:
        aliases:
          - pufferpanel
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
    # Restart policy
    restart: unless-stopped
  

volumes:
  pufferpanel_config:
  pufferpanel_data:

networks:
  cloud_internal:
    external: true