services:
  littlelink-app:
    build:
      context: ./littlelink/.
      dockerfile: Dockerfile
      args:
        repo: ${littlelink_git_repo:-https://github.com/FuffyPal/littlelink.git}
    container_name: littlelink-app
    restart: unless-stopped
    networks:
      - cloud_public
    ports:
      - "8080:8080"

networks:
  cloud_public:
    external: true
